nblog/urls.py
from django.conf.urls import include, static
from django.conf import settings
from django.urls import path
from django.contrib import admin
from nblog import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post-detail'),
    path('admin/', admin.site.urls),
    path('mdeditor/', include('mdeditor.urls')),
]

if settings.DEBUG:
    urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nblog/models.py
#!/usr/bin/env python
# coding: utf-8
# cc @ 2017-09-27

from django.db import models
from mdeditor.fields import MDTextField


class Tags(models.Model):
    """
    标签
    """

    name = models.CharField(max_length=200, verbose_name=u"标签名称")
    created_at = models.DateTimeField(
        verbose_name=u'创建时间', editable=False, auto_now_add=True
    )

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = verbose_name_plural = u"标签"


def m2mdefault():
    try:
        return [Tags.objects.first().pk]
    except:
        return []


class Posts(models.Model):
    """
    文章
    """

    TYPE_CHOICES = [(1, u'原创'), (2, u'转载')]

    title = models.CharField(max_length=200, verbose_name=u"文章标题")
    content = MDTextField(verbose_name='内容')
    link = models.CharField(max_length=200, verbose_name=u"原文地址", blank=True)
    tags = models.ManyToManyField(Tags, default=m2mdefault)
    blog_type = models.IntegerField(choices=TYPE_CHOICES, default=1)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=u'创建时间')

    class Meta:
        ordering = ['-created_at']
        verbose_name = verbose_name_plural = u"文章"

nblog/views.py
#!/usr/bin/env python
# coding: utf-8
# cc @ 2017-09-28

from __future__ import unicode_literals

from django.views.generic import ListView, DetailView
from django.db.models import Q

from .models import Posts

import logging
logger = logging.getLogger('django')


class HomeView(ListView):
    """
    首页
    """

    template_name = 'nblog/home.html'
    model = Posts
    paginate_by = 5

    def get_queryset(self, *args, **kwargs):
        tag = self.request.GET.get('tag')
        search = self.request.GET.get('search')
        if tag:
            return Posts.objects.filter(tags=tag)
        if search:
            return Posts.objects.filter(
                Q(title__contains=search) | Q(content__contains=search)
            )
        return Posts.objects.all()

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        search = self.request.GET.get('search', '')
        context['search'] = search
        # context['tag_list'] = Tags.objects.all()
        # tag = self.request.GET.get('tag')
        # if tag:
        #     context['tag'] = tag
        return context


class PostDetailView(DetailView):
    """
    文章详情
    """

    template_name = 'nblog/post.html'
    model = Posts
    context_object_name = 'post_detail'
    queryset = Posts.objects.all()

nblog/templates/nblog/base.html
<!DOCTYPE html>
{% load staticfiles i18n %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block subtitle %}{% endblock %}-{% trans '大表哥' %}</title>
  <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static '/css/main.css' %}">
  <link rel="stylesheet" href="{% static '/css/default.css' %}">
</head>
<body>
  <!--nav class="navbar navbar-expand-lg navbar-light cc-navbar">
    <div class="container">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">{% trans '' %}</a>
    </div>
  </nav -->
  <div class="banner">
    <a class='banner-title' href="/">大表哥的life</a>
    <div class="container">
      <form>
        <div class="input-group mb-3 search-group">
          <input type="text" name="search" class="form-control" placeholder="输入搜索内容" aria-label="Recipient's username" aria-describedby="button-addon2" value={{ search }}>
          <div class="input-group-append">
            <button class="btn btn-primary" type="submit" id="button-addon2">搜索</button>
          </div>
        </div>
      </form>
    </div>
  </div>
  <div class="container main-content">
    {% block main %}
    {% endblock %}
  </div>
  <div class="footer">
    <p class='icp'>
    <img src="{% static 'images/icp.svg' %}" alt=""/>
    <a href="http://www.beian.miit.gov.cn/" target='_blank'>京ICP备19050261号-1</a></p>
  </div>
  <script src="{% static 'valine/av-min.js' %}"></script>
  <script src="{% static 'valine/Valine.min.js' %}"></script>
  <script>
  </script>
  {% block js %}
  {% endblock %}
</body>
</html>

nblog/templates/nblog/home.html
{% extends 'nblog/base.html' %}
{% load staticfiles i18n %}
{% load helper %}
{% block subtitle %}{% trans '首页' %}{% endblock %}
{% block main%}
  <div class="row gutter">
    <div class="col">
      <div class="post-list">
      {% for i in posts_list %}
        <div class="post-item-fa shadow p-3 mb-5 bg-white rounded">
          <h3><a href="{% url 'post-detail' i.pk %}">{{ i.title }}</a></h3>
          <p class='top-attr'>
          <span>{{ i.created_at|date:'Y-m-d H:i:s' }}</span>
          </p>
          <div class="home-post-content">
            {{ i.content|md|safe }}
          </div>
          <p class='bottom-attr'>
          {% for t in i.tags.all %}
            <a href='{% url "home" %}?tag={{ t.id }}' class='badge badge-danger'>{{ t }}</a>
          {% endfor %}
          <span class="more">
            <a href="{% url 'post-detail' i.pk %}">{% trans '查看全文>>' %}</a>
          </span>
          </p>
        </div>
      {% endfor %}
      {% if is_paginated %}
        <nav aria-label="Page navigation example">
          <ul class="pagination">
          {% if page_obj.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}&tag={{ tag }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <a class="page-link" href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
          {% endif %}
          {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
              <li class="page-item active">
                <a class="page-link" href="#">{{ i }}<span class="sr-only">(current)</span></a>
              </li>
            {% else %}
              <li class="page-item"><a class="page-link" href="?page={{ i }}&tag={{ tag }}">{{ i }}</a></li>
            {% endif %}
          {% endfor %}

          {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.next_page_number }}&tag={{ tag }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <a class="page-link" href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
          {% endif %}
          </ul>
        </nav>
        <!-- ul class="pagination">
          {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}&tag={{ tag }}">&laquo;</a></li>
          {% else %}
            <li class="disabled"><span>&laquo;</span></li>
          {% endif %}
          {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
              <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
            {% else %}
              <li><a href="?page={{ i }}&tag={{ tag }}">{{ i }}</a></li>
            {% endif %}
          {% endfor %}
          {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}&tag={{ tag }}">&raquo;</a></li>
          {% else %}
            <li class="disabled"><span>&raquo;</span></li>
          {% endif %}
        </ul -->
      {% endif %}
      </div>
    </div>
    <!--div class="col-md-3 col-sm-3">
      <div class="tag-list">
        {% for tag in tag_list %}
          <a href="{% url 'home' %}?tag={{ tag.id }}" class='label label-default'>{{ tag.name }}</a>
        {% endfor %}
      </div>
    </div>
  </div -->
  {% block js %}
  {% endblock %}
{% endblock %}

nblog/templates/nblog/post.html
{% extends 'nblog/base.html' %}
{% load staticfiles i18n %}
{% load helper %}
{% block subtitle %}{{ post_detail.title }}{% endblock %}
{% block main%}
  <div class="row post-detail">
    <div class="col-md-12 col-sm-12">
      <h3 class='title'>{{ post_detail.title }}</h3>
      <div class="post-detail-content">
        {{ post_detail.content|md|safe }}
      </div>
    </div>
  </div>
  <div id="vcomments"></div>
{% endblock %}
{% block js %}
<script>
  new Valine({
    el: '#vcomments',
    appId: '{{ settings.VALINE_APPID }}',
    appKey: '{{ settings.VALINE_KEY }}',
    notify:false,
    verify:false,
    avatar:'mm',
    visitor: true,
    placeholder: '欢迎对本文章进行讨论~'
  });
</script>
{% endblock %}